/* Generated By:JavaCC: Do not edit this line. DotGrammar2Constants.java */
package grammatica;

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DotGrammar2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DUE_PUNTI = 8;
  /** RegularExpression Id. */
  int MAGGIORE = 9;
  /** RegularExpression Id. */
  int UGUALE = 10;
  /** RegularExpression Id. */
  int VIRGOLA = 11;
  /** RegularExpression Id. */
  int MINORE = 12;
  /** RegularExpression Id. */
  int PUNTO_E_VIRGOLA = 13;
  /** RegularExpression Id. */
  int PARENTESI_QUADRA_APERTA = 14;
  /** RegularExpression Id. */
  int PARENTESI_QUADRA_CHIUSA = 15;
  /** RegularExpression Id. */
  int PARENTESI_GRAFFA_APERTA = 16;
  /** RegularExpression Id. */
  int PARENTESI_GRAFFA_CHIUSA = 17;
  /** RegularExpression Id. */
  int ARCO = 18;
  /** RegularExpression Id. */
  int BACKSLASH = 19;
  /** RegularExpression Id. */
  int NODE = 20;
  /** RegularExpression Id. */
  int EDGE = 21;
  /** RegularExpression Id. */
  int DIGRAPH = 22;
  /** RegularExpression Id. */
  int GRAPH = 23;
  /** RegularExpression Id. */
  int SUBGRAPH = 24;
  /** RegularExpression Id. */
  int STRICT = 25;
  /** RegularExpression Id. */
  int RANKDIR = 26;
  /** RegularExpression Id. */
  int STYLE = 27;
  /** RegularExpression Id. */
  int COLOR = 28;
  /** RegularExpression Id. */
  int FONTSIZE = 29;
  /** RegularExpression Id. */
  int FILLCOLOR = 30;
  /** RegularExpression Id. */
  int HEIGHT = 31;
  /** RegularExpression Id. */
  int WIDTH = 32;
  /** RegularExpression Id. */
  int URL = 33;
  /** RegularExpression Id. */
  int LABEL = 34;
  /** RegularExpression Id. */
  int SHAPE = 35;
  /** RegularExpression Id. */
  int FONTNAME = 36;
  /** RegularExpression Id. */
  int FONTCOLOR = 37;
  /** RegularExpression Id. */
  int LABELFONTSIZE = 38;
  /** RegularExpression Id. */
  int LABELFONTNAME = 39;
  /** RegularExpression Id. */
  int BGCOLOR = 40;
  /** RegularExpression Id. */
  int PENCOLOR = 41;
  /** RegularExpression Id. */
  int DIR = 42;
  /** RegularExpression Id. */
  int TOOLTIP = 43;
  /** RegularExpression Id. */
  int DIGITS = 44;
  /** RegularExpression Id. */
  int DIGIT = 45;
  /** RegularExpression Id. */
  int LETTER = 46;
  /** RegularExpression Id. */
  int ESCAPED_QUOTES = 47;
  /** RegularExpression Id. */
  int ID = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "\":\"",
    "\">\"",
    "\"=\"",
    "\",\"",
    "\"<\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"->\"",
    "\"\\\"\"",
    "<NODE>",
    "<EDGE>",
    "<DIGRAPH>",
    "<GRAPH>",
    "<SUBGRAPH>",
    "<STRICT>",
    "<RANKDIR>",
    "\"style\"",
    "\"color\"",
    "\"fontsize\"",
    "\"fillcolor\"",
    "\"height\"",
    "\"width\"",
    "\"URL\"",
    "\"label\"",
    "\"shape\"",
    "\"fontname\"",
    "\"fontcolor\"",
    "\"labelfontsize\"",
    "\"labelfontname\"",
    "\"bgcolor\"",
    "\"pencolor\"",
    "\"dir\"",
    "\"tooltip\"",
    "<DIGITS>",
    "<DIGIT>",
    "<LETTER>",
    "<ESCAPED_QUOTES>",
    "<ID>",
  };

}
