/* Generated By:JavaCC: Do not edit this line. DotGrammarTokenManager.java */
package grammatica;
import utility.*;

/** Token Manager. */
public class DotGrammarTokenManager implements DotGrammarConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
<<<<<<< HEAD
         if ((active0 & 0x2020000000L) != 0L)
         {
            jjmatchedKind = 50;
            return 67;
         }
=======
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         if ((active0 & 0x40L) != 0L)
<<<<<<< HEAD
            return 88;
         if ((active0 & 0x10000L) != 0L)
            return 89;
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 50;
            return 31;
         }
         if ((active0 & 0x2fdfc0000000L) != 0L)
         {
            jjmatchedKind = 50;
            return 22;
         }
         if ((active0 & 0x8000L) != 0L)
            return 90;
=======
            return 81;
         if ((active0 & 0x1010000000L) != 0L)
         {
            jjmatchedKind = 49;
            return 60;
         }
         if ((active0 & 0x10000L) != 0L)
            return 82;
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 49;
            return 31;
         }
         if ((active0 & 0x17efe0000000L) != 0L)
         {
            jjmatchedKind = 49;
            return 22;
         }
         if ((active0 & 0x8000L) != 0L)
            return 83;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         return -1;
      case 1:
<<<<<<< HEAD
         if ((active0 & 0x2fffc0000000L) != 0L)
=======
         if ((active0 & 0x10000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 1;
<<<<<<< HEAD
            return 22;
=======
            return 68;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         }
<<<<<<< HEAD
         if ((active0 & 0x100000000000L) != 0L)
=======
         if ((active0 & 0x80000000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 1;
            return 32;
         }
<<<<<<< HEAD
         if ((active0 & 0x20000000L) != 0L)
=======
         if ((active0 & 0x17ffe0000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 1;
<<<<<<< HEAD
            return 75;
=======
            return 22;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         }
         return -1;
      case 2:
<<<<<<< HEAD
         if ((active0 & 0x100800000000L) != 0L)
            return 22;
         if ((active0 & 0x2ff7e0000000L) != 0L)
=======
         if ((active0 & 0x80400000000L) != 0L)
            return 22;
         if ((active0 & 0x17fbf0000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 2;
            return 22;
         }
         return -1;
      case 3:
<<<<<<< HEAD
         if ((active0 & 0x2ff7e0000000L) != 0L)
=======
         if ((active0 & 0x17fbf0000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 3;
            return 22;
         }
         return -1;
      case 4:
<<<<<<< HEAD
         if ((active0 & 0x2cc380000000L) != 0L)
=======
         if ((active0 & 0x19a30000000L) != 0L)
            return 22;
         if ((active0 & 0x1661c0000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
            if (jjmatchedPos != 4)
            {
<<<<<<< HEAD
               jjmatchedKind = 50;
=======
               jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
               jjmatchedPos = 4;
            }
            return 22;
         }
<<<<<<< HEAD
         if ((active0 & 0x33460000000L) != 0L)
            return 22;
=======
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         return -1;
      case 5:
<<<<<<< HEAD
         if ((active0 & 0x200000000L) != 0L)
            return 22;
         if ((active0 & 0x2fc180000000L) != 0L)
=======
         if ((active0 & 0x100000000L) != 0L)
            return 22;
         if ((active0 & 0x17e0c0000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 5;
            return 22;
         }
         return -1;
      case 6:
<<<<<<< HEAD
         if ((active0 & 0x240000000000L) != 0L)
            return 22;
         if ((active0 & 0xbc180000000L) != 0L)
=======
         if ((active0 & 0x120000000000L) != 0L)
            return 22;
         if ((active0 & 0x5e0c0000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 6;
            return 22;
         }
         return -1;
      case 7:
<<<<<<< HEAD
         if ((active0 & 0x84080000000L) != 0L)
            return 22;
         if ((active0 & 0x38100000000L) != 0L)
=======
         if ((active0 & 0x42040000000L) != 0L)
            return 22;
         if ((active0 & 0x1c080000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 7;
            return 22;
         }
         return -1;
      case 8:
<<<<<<< HEAD
         if ((active0 & 0x8100000000L) != 0L)
            return 22;
         if ((active0 & 0x30000000000L) != 0L)
=======
         if ((active0 & 0x18000000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 8;
            return 22;
         }
         if ((active0 & 0x4080000000L) != 0L)
            return 22;
         return -1;
      case 9:
<<<<<<< HEAD
         if ((active0 & 0x30000000000L) != 0L)
=======
         if ((active0 & 0x18000000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 9;
            return 22;
         }
         return -1;
      case 10:
<<<<<<< HEAD
         if ((active0 & 0x30000000000L) != 0L)
=======
         if ((active0 & 0x18000000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 10;
            return 22;
         }
         return -1;
      case 11:
<<<<<<< HEAD
         if ((active0 & 0x30000000000L) != 0L)
=======
         if ((active0 & 0x18000000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 50;
=======
            jjmatchedKind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 11;
            return 22;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 34:
<<<<<<< HEAD
         return jjStartNfaWithStates_0(0, 16, 89);
=======
         return jjStartNfaWithStates_0(0, 16, 82);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 44:
         return jjStopAtPos(0, 8);
      case 45:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 58:
         return jjStopAtPos(0, 5);
      case 59:
         return jjStopAtPos(0, 10);
      case 60:
         return jjStopAtPos(0, 9);
      case 61:
         return jjStopAtPos(0, 7);
      case 62:
<<<<<<< HEAD
         return jjStartNfaWithStates_0(0, 6, 88);
=======
         return jjStartNfaWithStates_0(0, 6, 81);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 85:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa1_0(0x800000000L);
=======
         return jjMoveStringLiteralDfa1_0(0x400000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 91:
         return jjStopAtPos(0, 11);
      case 93:
         return jjStopAtPos(0, 12);
      case 98:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0xc180000000L);
      case 104:
         return jjMoveStringLiteralDfa1_0(0x200000000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x31000000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x80000000000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x2020000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x400000000L);
=======
         return jjMoveStringLiteralDfa1_0(0x20000000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x80000000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x60c0000000L);
      case 104:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x18800000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x1010000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x100000000000L);
      case 119:
         return jjMoveStringLiteralDfa1_0(0x200000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 123:
         return jjStopAtPos(0, 13);
      case 125:
         return jjStopAtPos(0, 14);
      default :
         return jjMoveNfa_0(0, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 62:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(1, 15);
         break;
      case 82:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000L);
=======
         return jjMoveStringLiteralDfa2_0(active0, 0x400000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 97:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa2_0(active0, 0x31000000000L);
=======
         return jjMoveStringLiteralDfa2_0(active0, 0x18800000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 101:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa2_0(active0, 0x80200000000L);
=======
         return jjMoveStringLiteralDfa2_0(active0, 0x40100000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 103:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
=======
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 104:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000L);
=======
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 105:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa2_0(active0, 0x100500000000L);
=======
         return jjMoveStringLiteralDfa2_0(active0, 0x80280000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 111:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa2_0(active0, 0x20c0c0000000L);
=======
         return jjMoveStringLiteralDfa2_0(active0, 0x106060000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 116:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000L);
=======
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 76:
<<<<<<< HEAD
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(2, 35, 22);
=======
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(2, 34, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      case 97:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000L);
=======
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 98:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa3_0(active0, 0x31000000000L);
=======
         return jjMoveStringLiteralDfa3_0(active0, 0x18800000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 99:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x140000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x8c080000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000000L);
=======
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000000L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000L);
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0xa0000000L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x46040000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 114:
<<<<<<< HEAD
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 44, 22);
=======
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 43, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      case 121:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
=======
         return jjMoveStringLiteralDfa3_0(active0, 0x10000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 99:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000L);
=======
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 101:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa4_0(active0, 0x31000000000L);
=======
         return jjMoveStringLiteralDfa4_0(active0, 0x18800000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 103:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa4_0(active0, 0x200000000L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x200120000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x40040000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000000L);
=======
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x100090000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x20020000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 116:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa4_0(active0, 0xc480000000L);
=======
         return jjMoveStringLiteralDfa4_0(active0, 0x6240000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 99:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa5_0(active0, 0x8100000000L);
=======
         return jjMoveStringLiteralDfa5_0(active0, 0x4080000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 101:
<<<<<<< HEAD
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 22);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 37, 22);
=======
         if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(4, 28, 22);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 36, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      case 104:
<<<<<<< HEAD
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(4, 34, 22);
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000L);
=======
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(4, 33, 22);
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 108:
<<<<<<< HEAD
         if ((active0 & 0x1000000000L) != 0L)
=======
         if ((active0 & 0x800000000L) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         {
<<<<<<< HEAD
            jjmatchedKind = 36;
=======
            jjmatchedKind = 35;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
            jjmatchedPos = 4;
         }
<<<<<<< HEAD
         return jjMoveStringLiteralDfa5_0(active0, 0x70000000000L);
=======
         return jjMoveStringLiteralDfa5_0(active0, 0x38000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 110:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000L);
=======
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 111:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000L);
=======
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 114:
<<<<<<< HEAD
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(4, 30, 22);
=======
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(4, 29, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      case 115:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L);
=======
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 116:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa5_0(active0, 0x200000000000L);
=======
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 97:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000L);
=======
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 102:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa6_0(active0, 0x30000000000L);
=======
         return jjMoveStringLiteralDfa6_0(active0, 0x18000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 105:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa6_0(active0, 0x200080000000L);
=======
         return jjMoveStringLiteralDfa6_0(active0, 0x100040000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 108:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa6_0(active0, 0x80000000000L);
=======
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 111:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa6_0(active0, 0x48100000000L);
=======
         return jjMoveStringLiteralDfa6_0(active0, 0x24080000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 116:
<<<<<<< HEAD
         if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(5, 33, 22);
=======
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(5, 32, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 108:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa7_0(active0, 0x8100000000L);
=======
         return jjMoveStringLiteralDfa7_0(active0, 0x4080000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 109:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000000L);
=======
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 111:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa7_0(active0, 0xb0000000000L);
=======
         return jjMoveStringLiteralDfa7_0(active0, 0x58000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 112:
<<<<<<< HEAD
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 45, 22);
=======
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 44, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      case 114:
<<<<<<< HEAD
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 42, 22);
=======
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 41, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      case 122:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa7_0(active0, 0x80000000L);
=======
         return jjMoveStringLiteralDfa7_0(active0, 0x40000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 101:
<<<<<<< HEAD
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(7, 31, 22);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 38, 22);
=======
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(7, 30, 22);
         else if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 37, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      case 110:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa8_0(active0, 0x30000000000L);
=======
         return jjMoveStringLiteralDfa8_0(active0, 0x18000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 111:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa8_0(active0, 0x8100000000L);
=======
         return jjMoveStringLiteralDfa8_0(active0, 0x4080000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 114:
<<<<<<< HEAD
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 43, 22);
=======
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 42, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 114:
<<<<<<< HEAD
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(8, 32, 22);
         else if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 39, 22);
=======
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(8, 31, 22);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 38, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      case 116:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa9_0(active0, 0x30000000000L);
=======
         return jjMoveStringLiteralDfa9_0(active0, 0x18000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 110:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa10_0(active0, 0x20000000000L);
=======
         return jjMoveStringLiteralDfa10_0(active0, 0x10000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 115:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa10_0(active0, 0x10000000000L);
=======
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 97:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa11_0(active0, 0x20000000000L);
=======
         return jjMoveStringLiteralDfa11_0(active0, 0x10000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 105:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa11_0(active0, 0x10000000000L);
=======
         return jjMoveStringLiteralDfa11_0(active0, 0x8000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
   }
   switch(curChar)
   {
      case 109:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa12_0(active0, 0x20000000000L);
=======
         return jjMoveStringLiteralDfa12_0(active0, 0x10000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      case 122:
<<<<<<< HEAD
         return jjMoveStringLiteralDfa12_0(active0, 0x10000000000L);
=======
         return jjMoveStringLiteralDfa12_0(active0, 0x8000000000L);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      default :
         break;
   }
   return jjStartNfa_0(10, active0);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
   }
   switch(curChar)
   {
      case 101:
<<<<<<< HEAD
         if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 40, 22);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 41, 22);
=======
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 39, 22);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(12, 40, 22);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         break;
      default :
         break;
   }
   return jjStartNfa_0(11, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
<<<<<<< HEAD
   jjnewStateCnt = 88;
=======
   jjnewStateCnt = 81;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
<<<<<<< HEAD
               case 67:
               case 22:
=======
               case 32:
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(22);
                  break;
               case 68:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(22);
                  break;
               case 83:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  else if (curChar == 46)
                     jjCheckNAdd(17);
                  break;
               case 82:
                  if ((0xfffffffaffffd9ffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 34)
                  {
                     if (kind > 49)
                        kind = 49;
                  }
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(22);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(22);
                  break;
               case 81:
                  if ((0xfffffffeffffd9ffL & l) != 0L)
                     jjCheckNAddTwoStates(28, 29);
                  if (curChar == 60)
                  {
                     if (kind > 49)
                        kind = 49;
                  }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  else if (curChar == 62)
                     jjCheckNAddTwoStates(28, 29);
                  else if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 46)
                     jjCheckNAdd(17);
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(16, 18);
                  break;
               case 15:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(16, 18);
                  break;
               case 16:
                  if (curChar == 46)
                     jjCheckNAdd(17);
                  break;
               case 17:
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
<<<<<<< HEAD
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(22);
=======
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(17);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
<<<<<<< HEAD
               case 32:
=======
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 19:
                  if (curChar != 46)
                     break;
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(20);
                  break;
               case 20:
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
<<<<<<< HEAD
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(22);
=======
                  if (kind > 49)
                     kind = 49;
                  jjCheckNAdd(20);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
<<<<<<< HEAD
               case 31:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(22);
                  break;
               case 90:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  else if (curChar == 46)
                     jjCheckNAdd(17);
                  break;
               case 89:
                  if ((0xfffffffaffffd9ffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 34)
                  {
                     if (kind > 50)
                        kind = 50;
                  }
                  break;
               case 75:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(22);
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  else if (curChar == 62)
                     jjCheckNAddTwoStates(28, 29);
                  else if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  else if (curChar == 46)
                     jjCheckNAdd(17);
                  else if (curChar == 45)
                     jjCheckNAddTwoStates(16, 18);
                  break;
               case 88:
                  if ((0xfffffffeffffd9ffL & l) != 0L)
                     jjCheckNAddTwoStates(28, 29);
                  if (curChar == 60)
                  {
                     if (kind > 50)
                        kind = 50;
                  }
                  break;
               case 15:
                  if (curChar == 45)
                     jjCheckNAddTwoStates(16, 18);
                  break;
               case 16:
                  if (curChar == 46)
                     jjCheckNAdd(17);
                  break;
               case 17:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(17);
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(18, 19);
                  break;
               case 19:
                  if (curChar != 46)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(20);
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(20);
                  break;
=======
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
               case 23:
                  if (curChar == 34)
                     jjCheckNAddStates(0, 2);
                  break;
               case 24:
                  if ((0xfffffffaffffd9ffL & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 26:
<<<<<<< HEAD
                  if (curChar == 34 && kind > 50)
                     kind = 50;
=======
                  if (curChar == 34 && kind > 49)
                     kind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
               case 27:
                  if (curChar == 62)
                     jjCheckNAddTwoStates(28, 29);
                  break;
               case 28:
                  if ((0xfffffffeffffd9ffL & l) != 0L)
                     jjCheckNAddTwoStates(28, 29);
                  break;
               case 29:
<<<<<<< HEAD
                  if (curChar == 60 && kind > 50)
                     kind = 50;
=======
                  if (curChar == 60 && kind > 49)
                     kind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
<<<<<<< HEAD
               case 67:
=======
               case 32:
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
<<<<<<< HEAD
                     if (kind > 50)
                        kind = 50;
=======
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(22);
                  }
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 68:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                     jjCheckNAdd(22);
                  }
<<<<<<< HEAD
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  else if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 75;
                  else if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
=======
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
<<<<<<< HEAD
               case 32:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(22);
                  }
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 52;
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 31:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(22);
                  }
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 45;
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 89:
=======
               case 82:
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  jjCheckNAddStates(0, 2);
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
<<<<<<< HEAD
               case 75:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 50)
                        kind = 50;
                     jjCheckNAdd(22);
                  }
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
=======
               case 60:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(22);
                  }
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  else if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
                  else if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 31:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 49)
                        kind = 49;
                     jjCheckNAdd(22);
                  }
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 45;
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 81:
               case 28:
                  jjCheckNAddTwoStates(28, 29);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
               case 0:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
<<<<<<< HEAD
                     if (kind > 50)
                        kind = 50;
=======
                     if (kind > 49)
                        kind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                     jjCheckNAdd(22);
                  }
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(3, 5);
                  else if ((0x8000000080L & l) != 0L)
                     jjAddStates(6, 7);
                  else if ((0x1000000010L & l) != 0L)
<<<<<<< HEAD
                     jjAddStates(8, 11);
=======
                     jjAddStates(8, 10);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  else if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  else if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  else if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
<<<<<<< HEAD
               case 88:
               case 28:
                  jjCheckNAddTwoStates(28, 29);
                  break;
=======
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
               case 1:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 2:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 3:
                  if ((0x2000000020L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 4:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 5:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 7:
                  if ((0x2000000020L & l) != 0L && kind > 18)
                     kind = 18;
                  break;
               case 8:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 9:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 10:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 11:
                  if ((0x80000000800L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 12:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 13:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 14:
                  if ((0x4000000040000L & l) != 0L && kind > 24)
                     kind = 24;
                  break;
               case 21:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
<<<<<<< HEAD
                  if (kind > 50)
                     kind = 50;
=======
                  if (kind > 49)
                     kind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  jjCheckNAdd(22);
                  break;
               case 22:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
<<<<<<< HEAD
                  if (kind > 50)
                     kind = 50;
=======
                  if (kind > 49)
                     kind = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  jjCheckNAdd(22);
                  break;
               case 24:
                  jjCheckNAddStates(0, 2);
                  break;
               case 25:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 30:
                  if ((0x1000000010L & l) != 0L)
<<<<<<< HEAD
                     jjAddStates(8, 11);
=======
                     jjAddStates(8, 10);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
               case 33:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 34:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 35:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 36:
                  if ((0x10000000100L & l) != 0L && kind > 19)
                     kind = 19;
                  break;
               case 37:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 38;
                  break;
               case 38:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 39:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 40;
                  break;
               case 40:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 41;
                  break;
               case 41:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if ((0x10000000100L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 43;
                  break;
               case 43:
                  if (curChar == 95 && kind > 20)
                     kind = 20;
                  break;
               case 44:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 45:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 46:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 47:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 48:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 49:
                  if ((0x800000008000L & l) != 0L && kind > 27)
                     kind = 27;
                  break;
               case 50:
<<<<<<< HEAD
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 51;
=======
                  if ((0x8000000080L & l) != 0L)
                     jjAddStates(6, 7);
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
               case 51:
<<<<<<< HEAD
                  if ((0x8000000080L & l) != 0L)
=======
                  if ((0x4000000040000L & l) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 52:
<<<<<<< HEAD
                  if ((0x4000000040000L & l) != 0L)
=======
                  if ((0x200000002L & l) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 53:
<<<<<<< HEAD
                  if ((0x200000002L & l) != 0L)
=======
                  if ((0x1000000010000L & l) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 54:
<<<<<<< HEAD
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 55;
=======
                  if ((0x10000000100L & l) != 0L && kind > 21)
                     kind = 21;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
               case 55:
<<<<<<< HEAD
                  if ((0x800000008000L & l) != 0L)
=======
                  if ((0x4000000040000L & l) != 0L)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 56:
<<<<<<< HEAD
                  if (curChar == 95 && kind > 28)
                     kind = 28;
=======
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 57:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 58:
                  if ((0x800000008000L & l) != 0L && kind > 25)
                     kind = 25;
                  break;
               case 59:
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(3, 5);
                  break;
               case 61:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 62:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 64:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 66:
                  if ((0x10000000100L & l) != 0L && kind > 22)
                     kind = 22;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
<<<<<<< HEAD
               case 57:
                  if ((0x8000000080L & l) != 0L)
                     jjAddStates(6, 7);
                  break;
               case 58:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 59;
=======
               case 67:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 68;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
<<<<<<< HEAD
               case 59:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 60;
=======
               case 69:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
<<<<<<< HEAD
               case 60:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
=======
               case 70:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  break;
<<<<<<< HEAD
               case 61:
                  if ((0x10000000100L & l) != 0L && kind > 21)
                     kind = 21;
                  break;
               case 62:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 64:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x800000008000L & l) != 0L && kind > 25)
                     kind = 25;
                  break;
               case 66:
                  if ((0x8000000080000L & l) != 0L)
                     jjAddStates(3, 5);
                  break;
               case 68:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 69:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 70:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 71:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 72:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x10000000100L & l) != 0L && kind > 22)
                     kind = 22;
                  break;
               case 74:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 76:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 78:
=======
               case 71:
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  if ((0x10000000100000L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
<<<<<<< HEAD
               case 79:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 81:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 82;
                  break;
               case 82:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 83;
                  break;
               case 83:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 84;
                  break;
               case 84:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 85:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 86:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 87:
=======
               case 72:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 73:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 74:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 75:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 76;
                  break;
               case 76:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 77:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 78;
                  break;
               case 78:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 79;
                  break;
               case 79:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 80:
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
                  if ((0x800000008000L & l) != 0L && kind > 26)
                     kind = 26;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
<<<<<<< HEAD
               case 89:
=======
               case 82:
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
               case 24:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
<<<<<<< HEAD
               case 88:
=======
               case 81:
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
               case 28:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(28, 29);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
<<<<<<< HEAD
      if ((i = jjnewStateCnt) == (startsAt = 88 - (jjnewStateCnt = startsAt)))
=======
      if ((i = jjnewStateCnt) == (startsAt = 81 - (jjnewStateCnt = startsAt)))
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
<<<<<<< HEAD
   24, 25, 26, 67, 74, 79, 58, 62, 31, 37, 44, 50, 
=======
   24, 25, 26, 60, 67, 72, 51, 55, 31, 37, 44, 
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, "\72", "\76", "\75", "\54", "\74", "\73", "\133", 
"\135", "\173", "\175", "\55\76", "\42", null, null, null, null, null, null, null, 
<<<<<<< HEAD
null, null, null, null, null, "\163\164\171\154\145", "\143\157\154\157\162", 
=======
null, null, null, null, "\163\164\171\154\145", "\143\157\154\157\162", 
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
"\146\157\156\164\163\151\172\145", "\146\151\154\154\143\157\154\157\162", "\150\145\151\147\150\164", 
"\167\151\144\164\150", "\125\122\114", "\154\141\142\145\154", "\163\150\141\160\145", 
"\146\157\156\164\156\141\155\145", "\146\157\156\164\143\157\154\157\162", 
"\154\141\142\145\154\146\157\156\164\163\151\172\145", "\154\141\142\145\154\146\157\156\164\156\141\155\145", 
"\142\147\143\157\154\157\162", "\160\145\156\143\157\154\157\162", "\144\151\162", 
"\164\157\157\154\164\151\160", null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
<<<<<<< HEAD
   0x43fffffffffe1L, 
=======
   0x21fffffffffe1L, 
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
<<<<<<< HEAD
private final int[] jjrounds = new int[88];
private final int[] jjstateSet = new int[176];
=======
private final int[] jjrounds = new int[81];
private final int[] jjstateSet = new int[162];
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
protected char curChar;
/** Constructor. */
public DotGrammarTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public DotGrammarTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
<<<<<<< HEAD
   for (i = 88; i-- > 0;)
=======
   for (i = 81; i-- > 0;)
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
