/* Generated By:JavaCC: Do not edit this line. DotGrammarConstants.java */
package grammatica;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DotGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DUE_PUNTI = 5;
  /** RegularExpression Id. */
  int MAGGIORE = 6;
  /** RegularExpression Id. */
  int UGUALE = 7;
  /** RegularExpression Id. */
  int VIRGOLA = 8;
  /** RegularExpression Id. */
  int MINORE = 9;
  /** RegularExpression Id. */
  int PUNTO_E_VIRGOLA = 10;
  /** RegularExpression Id. */
  int PARENTESI_QUADRA_APERTA = 11;
  /** RegularExpression Id. */
  int PARENTESI_QUADRA_CHIUSA = 12;
  /** RegularExpression Id. */
  int PARENTESI_GRAFFA_APERTA = 13;
  /** RegularExpression Id. */
  int PARENTESI_GRAFFA_CHIUSA = 14;
  /** RegularExpression Id. */
  int ARCO = 15;
  /** RegularExpression Id. */
  int BACKSLASH = 16;
  /** RegularExpression Id. */
  int NODE = 17;
  /** RegularExpression Id. */
  int EDGE = 18;
  /** RegularExpression Id. */
  int DIGRAPH = 19;
  /** RegularExpression Id. */
  int DIGRAPH_ = 20;
  /** RegularExpression Id. */
  int GRAPH = 21;
  /** RegularExpression Id. */
  int SUBGRAPH = 22;
  /** RegularExpression Id. */
  int STRICT = 23;
  /** RegularExpression Id. */
  int RANKDIR = 24;
  /** RegularExpression Id. */
  int GRAFO = 25;
  /** RegularExpression Id. */
  int SOTTOGRAFO = 26;
  /** RegularExpression Id. */
  int DIGRAFO = 27;
  /** RegularExpression Id. */
<<<<<<< HEAD
  int DIGRAFO_ = 28;
=======
  int STYLE = 28;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int STYLE = 29;
=======
  int COLOR = 29;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int COLOR = 30;
=======
  int FONTSIZE = 30;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int FONTSIZE = 31;
=======
  int FILLCOLOR = 31;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int FILLCOLOR = 32;
=======
  int HEIGHT = 32;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int HEIGHT = 33;
=======
  int WIDTH = 33;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int WIDTH = 34;
=======
  int URL = 34;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int URL = 35;
=======
  int LABEL = 35;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int LABEL = 36;
=======
  int SHAPE = 36;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int SHAPE = 37;
=======
  int FONTNAME = 37;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int FONTNAME = 38;
=======
  int FONTCOLOR = 38;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int FONTCOLOR = 39;
=======
  int LABELFONTSIZE = 39;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int LABELFONTSIZE = 40;
=======
  int LABELFONTNAME = 40;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int LABELFONTNAME = 41;
=======
  int BGCOLOR = 41;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int BGCOLOR = 42;
=======
  int PENCOLOR = 42;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int PENCOLOR = 43;
=======
  int DIR = 43;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int DIR = 44;
=======
  int TOOLTIP = 44;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int TOOLTIP = 45;
=======
  int DIGITS = 45;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
  /** RegularExpression Id. */
<<<<<<< HEAD
  int DIGITS = 46;
  /** RegularExpression Id. */
  int DIGIT = 47;
  /** RegularExpression Id. */
  int LETTER = 48;
  /** RegularExpression Id. */
  int ESCAPED_QUOTES = 49;
  /** RegularExpression Id. */
  int ID = 50;
=======
  int DIGIT = 46;
  /** RegularExpression Id. */
  int LETTER = 47;
  /** RegularExpression Id. */
  int ESCAPED_QUOTES = 48;
  /** RegularExpression Id. */
  int ID = 49;
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":\"",
    "\">\"",
    "\"=\"",
    "\",\"",
    "\"<\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"->\"",
    "\"\\\"\"",
    "<NODE>",
    "<EDGE>",
    "<DIGRAPH>",
    "<DIGRAPH_>",
    "<GRAPH>",
    "<SUBGRAPH>",
    "<STRICT>",
    "<RANKDIR>",
    "<GRAFO>",
    "<SOTTOGRAFO>",
    "<DIGRAFO>",
<<<<<<< HEAD
    "<DIGRAFO_>",
=======
>>>>>>> branch 'master' of https://github.com/oconeluciano84/Dot2Metric.git
    "\"style\"",
    "\"color\"",
    "\"fontsize\"",
    "\"fillcolor\"",
    "\"height\"",
    "\"width\"",
    "\"URL\"",
    "\"label\"",
    "\"shape\"",
    "\"fontname\"",
    "\"fontcolor\"",
    "\"labelfontsize\"",
    "\"labelfontname\"",
    "\"bgcolor\"",
    "\"pencolor\"",
    "\"dir\"",
    "\"tooltip\"",
    "<DIGITS>",
    "<DIGIT>",
    "<LETTER>",
    "<ESCAPED_QUOTES>",
    "<ID>",
  };

}
